version: "3.9"
services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT_DEFAULT}:${DB_PORT}"
  web:
    build:
      context: .
      args:
        BUILDKIT_INLINE_CACHE: "1"
        DOCKER_BUILDKIT: "1"
    depends_on:
      - db
    ports:
      - "${APP_PORT}:${APP_PORT}"
