version: "3.9"
services:
  db:
    image: postgres:13.6
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypass21!"
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8899:8899"
